/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SecurityGonago;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class InterfazLoginSG extends javax.swing.JFrame {

    DateFormat dateFormatMDY = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    public InterfazLoginSG() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        setTitle("SecurityGonago");
        TypeUserLogin.addItem("Alumno");
        TypeUserLogin.addItem("Maestro");
        TypeWorkshopLogin.addItem("Aula de idiomas");
        TypeWorkshopLogin.addItem("Biblioteca/Laboratorio de computo");
        TypeWorkshopLogin.addItem("Desarrollo de negocios area de diseño");
        TypeWorkshopLogin.addItem("procesos industriales/Taller de computo");
        TypeWorkshopLogin.addItem("Laboratorio de redes");
        TypeWorkshopLogin.addItem("Area de computo");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo_C.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        InputEmailLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InputPasswordLogin = new javax.swing.JTextField();
        TypeUserLogin = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TypeWorkshopLogin = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EquipmentUsedLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        InputIdLogin = new javax.swing.JTextField();
        InputDateLogin = new com.toedter.calendar.JDateChooser();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Correo");

        InputEmailLogin.setBackground(new java.awt.Color(0, 102, 102));
        InputEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailLoginActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Contraseña");

        InputPasswordLogin.setBackground(new java.awt.Color(0, 102, 102));
        InputPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPasswordLoginActionPerformed(evt);
            }
        });

        TypeUserLogin.setBackground(new java.awt.Color(0, 255, 255));
        TypeUserLogin.setForeground(new java.awt.Color(0, 51, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));

        ButtonLogin.setBackground(new java.awt.Color(0, 255, 255));
        ButtonLogin.setForeground(new java.awt.Color(0, 51, 51));
        ButtonLogin.setText("Ingresar");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Ingreso");

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(130, 130, 130)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TypeWorkshopLogin.setBackground(new java.awt.Color(0, 255, 255));
        TypeWorkshopLogin.setForeground(new java.awt.Color(0, 51, 51));
        TypeWorkshopLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeWorkshopLoginActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Fecha");

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Equipo Usado");

        EquipmentUsedLogin.setBackground(new java.awt.Color(0, 102, 102));
        EquipmentUsedLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentUsedLoginActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Matricula");

        InputIdLogin.setBackground(new java.awt.Color(0, 102, 102));
        InputIdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIdLoginActionPerformed(evt);
            }
        });

        InputDateLogin.setDateFormatString("dd MM yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputIdLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(EquipmentUsedLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(TypeWorkshopLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputDateLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(TypeWorkshopLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(InputIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipmentUsedLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputDateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLogin)
                        .addGap(134, 134, 134))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordLoginActionPerformed

    private void InputEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailLoginActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed

        String Workshop = TypeWorkshopLogin.getSelectedItem().toString();
        String Id = InputIdLogin.getText();
        String Equipment = EquipmentUsedLogin.getText();
        String date = InputDateLogin.getDate().toString();
//        JOptionPane.showMessageDialog(this, );

        conectar cc = new conectar();
        Connection cb = cc.bitacora();
        try {
//             INSERT INTO `bitacora`.`Fecha` (`Fecha`) VALUES ('Fri Mar 18 12:54:23 CST 2022');
//             INSERT INTO `bitacora`.`Bitacora` (`Id_Taller`, `Id_fecha`, `Equipo_usado`) VALUES ('Area de computo', '2', 'Computadora 2');

            PreparedStatement pst = cb.prepareStatement("INSERT INTO Bitacora(Id_Taller,Equipo_usado,Matricula) VALUES(?,?,?);");
            pst.setString(1, Workshop);
            pst.setString(2, Equipment);
            pst.setString(3, Id);

            PreparedStatement pst2 = cb.prepareStatement("INSERT INTO Fecha(FechaHora) VALUES (?);");
            pst2.setString(1, date);

            int b = pst2.executeUpdate();
            int a = pst.executeUpdate();

            if (a > 0 && b > 0) {
                JOptionPane.showMessageDialog(this, "Registro exitoso");
            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }        // TODO 
//        JOptionPane.showMessageDialog(this, "BIENVENIDO" + TypeUser + Workshop + Id + Email + Password + Equipment + Date);
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        InterfazSG v1 = new InterfazSG();
        v1.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String[] Usuario = {"Alumno", "Maestro"};
        JComboBox Tipos = new JComboBox(Usuario);
        Tipos.setBounds(20, 20, 100, 30);

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void EquipmentUsedLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentUsedLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipmentUsedLoginActionPerformed

    private void InputIdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIdLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIdLoginActionPerformed

    private void TypeWorkshopLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeWorkshopLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeWorkshopLoginActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginSG.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginSG.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginSG.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLoginSG.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLoginSG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JTextField EquipmentUsedLogin;
    private com.toedter.calendar.JDateChooser InputDateLogin;
    private javax.swing.JTextField InputEmailLogin;
    private javax.swing.JTextField InputIdLogin;
    private javax.swing.JTextField InputPasswordLogin;
    private javax.swing.JComboBox<String> TypeUserLogin;
    private javax.swing.JComboBox<String> TypeWorkshopLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void mostrardatos(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
